### ISSUE TITLE
爬虫Demo 爬取电影天堂

### ISSUE THREAD

**Issue by su37josephxia** [su37josephxia/Daydayup#48]
- 产出demo

**Comment by django-d** [comment]
想做 +1

**Comment by 605572714** [comment]
+1

**Comment by su37josephxia** [comment]
> 想做 +1

已加核心组

**Comment by su37josephxia** [comment]
> +1

赶紧认领一个任务

**Comment by 605572714** [comment]
project 无法 convert to issue啊

**Comment by startgain** [comment]
+1

**Comment by django-d** [comment]
> * 产出demo
领取任务的话是新建一个 issue 还是在这里回复就好了

**Comment by 605572714** [comment]
匿名爬取b栈 - 点赞 、浏览数-我想做这个，我提不了issue

**Comment by su37josephxia** [comment]
> 匿名爬取b栈 - 点赞 、浏览数-我想做这个，我提不了issue



> +1

    已经邀请

**Comment by 605572714** [comment]
> > 匿名爬取b栈 - 点赞 、浏览数-我想做这个，我提不了issue
> 
> > +1
> 
>     已经邀请

看到了，被邮箱当做垃圾邮件处理了，大家也都看下是不是邮件被当成了垃圾邮件

**Comment by wzhaofei** [comment]
+1
