### ISSUE TITLE
匿名爬取b栈 - 点赞 、浏览数

### ISSUE THREAD

**Issue by 605572714** [su37josephxia/Daydayup#51]
- 产出：代码

**Comment by su37josephxia** [comment]
这个没有link PR

**Comment by su37josephxia** [comment]
没有link PR

另外你这个程序会报错呀
![image](https://user-images.githubusercontent.com/9651900/142995956-c96c342b-6b75-46fc-a63c-8cd2918aa73b.png)

**Comment by 605572714** [comment]
然叔，目前最首要的就是这个问题，我这个代码是可以拿到数据，但是，这个EmbedPlayer我没找到有什么插件可以解决，我是在使用JSDOM的时候出现的这个问题，看提示是node没有能力识别embed标签。
